### ISSUE TITLE
maven library missing

### ISSUE THREAD

**Issue by ygxiao** [elbosso/swinginspector#1]
Hi Jürgen,

I tried to load the project, but seems the maven libraries it depends on are no longer available. Could you advise how to get it working? Thanks in advance.

Regards,
YG

**Comment by elbosso** [comment]
Hi, sorry I forgot to hit commit and push after adjusting the versions. The should be corrected by now

**Comment by ygxiao** [comment]
Thank you so much! It all works now.

Regards,
YG
