### ISSUE TITLE
maven library missing

### ISSUE THREAD

**Issue by carvalhogsc** [elbosso/swinginspector#8]
Unable to install dependencies, dependency repository is out of date. Are you still maintaining the project?

**Comment by elbosso** [comment]
thank you for noticing - i forgot to push the new dependencies. But this gave me the incentives needed to set up an CI CD pipeline to detect these kinds of failures in the future. The build now works [here](https://github.com/elbosso/swinginspector/actions/runs/8068170016/job/22040562223) and should do so at your machine, too.

And yes, i am still maintaining it...
